---
title: "Programming Assignment 1"
author: "Collin Mitchell"
date: "September 19, 2015"
output: html_document
---


## Variables
```{r}
baseurl      <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip"
file.dir     <- "./data"
completepath <- paste(file.dir, "/data.zip", sep = "")
weekday.list <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")

cumulativeSums            <- 0
cumulativeMeans           <- 0
cumulativeMedians         <- 0
cumulativeInterval        <- 0
cumulativeFixedMeans      <- 0
cumulativeFixedMedians    <- 0
cumulativeWeekendInterval <- 0
cumulativeWeekdayInterval <- 0

## Libraries
library(dplyr)
library(reshape2)
```


```{r}
# Prepare environment for data and get data.
if(!file.exists(file.dir)){ dir.create("./data")}

#download.file(baseurl, destfile = completepath)
#filename <- unzip(completepath, exdir=file.dir)
data <- read.csv("activity.csv")


# Arrange Data based on the dates.
data <- arrange(data, date)
```


```{r}
# Challenge 1
# mean steps per day?
## Ignore NA values (.., rm.na = T)
index = 1

for(distinctdates in levels(data$date)){
  temp <- filter(data, date == distinctdates)
  cumulativeSums[index] = sum(temp$steps, rm.na = T)
  index <- index + 1
}

# Histogram of values
print( factor(cumulativeSums) )
length(cumulativeSums)
hist(cumulativeSums)


# Report mean & median steps/day
index = 1
for(distinctdates in levels(data$date)){
  temp <- filter(data, date == distinctdates)
  cumulativeMeans[index] = mean(temp$steps, rm.na = T)
  index <- index + 1
}

length(cumulativeMeans)

index = 1
for(distinctdates in levels(data$date)){
  temp <- filter(data, date == distinctdates)
  cumulativeMedians[index] = median(temp$steps)
  index <- index + 1
}

length(cumulativeMedians)
```


```{r}
# Report results.
print(cumulativeMeans)
print(cumulativeMedians)

# Challenge 3
# Time series plot: 5-minute interval, avg steps taken, across all days
# Which 5 minute interval has the most steps.

splitOnInterval <- dcast(data, date + steps ~ interval)

for(index in 3:ncol(splitOnInterval) ){
  cumulativeInterval[index-2] <- sum(splitOnInterval[,index], na.rm = T)
}

# Fix the plot labels, but otherwise done.
plot(colnames(splitOnInterval)[3:length(splitOnInterval)], cumulativeInterval, type = "l")
```



```{r}
# I wanted the solution to be generic:
colnames(splitOnInterval)[match(max(cumulativeInterval), cumulativeInterval) + 2]

# Challenge 4
# n of NAs in data?
# deal with NA's in data and substitute solution in copy of data
sum(is.na(data$steps))

copyData <- data.frame(steps = NA, date = NA, interval = NA)

for(distinctdates in levels(data$date)){
  tempData <- filter(data, date == distinctdates)
  fillmean <- mean(tempData$steps, rm.na = T)
  print(distinctdates)
  
  #Don't forget about this exception
  if(is.na(fillmean)){ fillmean = 0}
  
  while(sum(is.na(tempData$steps))){
    target <- match(NA, tempData$steps)
    print(tempData$steps[target])
    tempData$steps[target] <- fillmean
    print(target)
  }
  
  if(nrow(copyData) == 1){ copyData <- tempData}
  else{
    copyData <- rbind(copyData, tempData)
  }

}
```



```{r}
# Histogram of number of steps/day
# calculate mean/median again.
# Different from before?
index = 1
for(distinctdates in levels(copyData$date)){
  temp <- filter(copyData, date == distinctdates)
  cumulativeFixedMeans[index] = mean(temp$steps, rm.na = T)
  index <- index + 1
}

length(cumulativeFixedMeans)

index = 1
for(distinctdates in levels(copyData$date)){
  temp <- filter(copyData, date == distinctdates)
  cumulativeFixedMedians[index] = median(temp$steps)
  index <- index + 1
}

length(cumulativeFixedMedians)
```


```{r}
# Challenge 6 | NEW DATASET
# //Weekdays() funct.
# Create factor variable in new dataset (weekday, weekend)
##  if day %in% ("Monday-Friday") = weekday
##  else weekend
# Panel plot| 5 minute interval steps/day wkend vs wkday.


# You might take points off for this, but there is a much easier way to do this than factors:
mutateDate <- mutate(copyData, weekday = weekdays(as.Date(date)) %in% weekday.list)


splitOnFixedInterval <- dcast(copyData, date + steps + weekday ~ interval)
weekendData  <- filter(splitOnFixedInterval, weekday == FALSE)
weekdayData  <- filter(splitOnFixedInterval, weekday == TRUE)

index <- 1
for(index in 3:ncol(weekendData) ){
  cumulativeWeekendInterval[index-2] <- sum(weekendData[,index], na.rm = T)
}

index <- 1
for(index in 3:ncol(weekdayData) ){
  cumulativeWeekdayInterval[index-2] <- sum(weekdayData[,index], na.rm = T)
}

par(mfrow = c(2,1))

# Fix the plot labels, but otherwise done.
plot(colnames(weekendData)[3:length(weekendData)], cumulativeWeekendInterval, type = "l")
plot(colnames(weekdayData)[3:length(weekdayData)], cumulativeWeekdayInterval, type = "l")
```

