---
title: 'Motor Trend: Picking Manual or Transmission'
author: "Collin Mitchell"
date: "October 21, 2015"
output: pdf_document
---
# Qualifications
You work for Motor Trend, a magazine about the automobile industry. Looking at a data set of a collection of cars, they are interested in exploring the relationship between a set of variables and miles per gallon (MPG) (outcome). They are particularly interested in the following two questions:

"Is an automatic or manual transmission better for MPG"
"Quantify the MPG difference between automatic and manual transmissions"

Your report must be:

Written as a PDF printout of a compiled (using knitr) R markdown document.
Brief. Roughly the equivalent of 2 pages or less for the main text. Supporting figures in an appendix can be included up to 5 total pages including the 2 for the main report. The appendix can only include figures.
Include a first paragraph executive summary.

vs = cylinder alignment


```{r}
data(mtcars)
carData <- mtcars
attach(mtcars)
library(dplyr)
library(ggplot2)

AUTOMATIC <- 0
MANUAL    <- 1

# Clean up column names
colnames(mtcars) <- c("mpg", "cylinders", "displacement", "horsepower", "axleratio", "weight", ".25milerun", "", "transmission", "gears", "carburetors")

# store for computing lm's
values <- vector()
for(item in colnames(mtcars)[2:11]){ values <- c(values, as.symbol(item))}

manualData <- filter(mtcars, am == MANUAL)
autoData   <- filter(mtcars, am == AUTOMATIC)

computeLM <- function(varName){
  return( lm(mpg ~ varname))
}
```

## Conlusion


- Get a special function to iterate through and store lm models.
- Split Data into Automatic and Manual transmission.
- 
